### ISSUE TITLE
activity无法回收？

### ISSUE THREAD

**Issue by singobana** [Hitomis/ActivitySwitcher#3]
ActivityManager持有了Activity的引用，这样会引起内存泄露或者Activity无法回收吧？

**Comment by Hitomis** [comment]
问的不错，其实这个问题你可以亲自试一试，你不停点击下一页，然后打开  ActivitySwitcher ，一个一个 Activity 的关闭掉，再不停打开，不停重复这个步骤，同时你注意 check 一下 AndroidStudio 的 Monitors 看有没有OOM。答案是没有~

ActivityManager 是持有 Activity 的引用，但是 Activity 也只是保存在ActivityManager  中的 Stack 里面，当 Activity 被关闭的时候，我会将该 Activity 从 Stack 中移除，之后并没有对象在引用该 Activity 。所以并不会发生OOM。具体可以仔细看看 or 调试一下 ActivitySwitcherHelper 中的代码。

**Comment by singobana** [comment]
OK 感谢回复 我看一下
